repos:
  - repo: local
    hooks:
      - id: pylint-src
        name: pylint (source)
        entry: pylint
        language: system
        files: ^rpi_tempmon/.*\.py$
        args: ["--fail-under=10.0"]
 
      - id: pylint-tests
        name: pylint (tests)
        entry: pylint
        language: system
        files: ^tests/.*\.py$
        args: ["--fail-under=10.0", "--rcfile=tests/.pylintrc"]
